---
title: "CA Gas Forecase"
author: "ClareCallahan"
date: "4/11/2021"
output: html_document
---

Data was pulled on 4/11/2021 from the EIA https://www.eia.gov/dnav/pet/PET_PRI_GND_DCUS_SCA_M.htm
Values are in $/Gallon of averaged Regular Gas formulations in CA from Jan 1995-Mar 2021 

```{r}

#install.packages('forecast', dependencies = TRUE)

```



```{r}
library(ggplot2)
library(readr)
library(tidyverse)
library(lubridate)
library(forecast)
library(tseries)
library(dplyr)
library(mgcv)
library(astsa)

```

```{r}
temp <- tempfile()
download.file("http://download.geonames.org/export/zip/US.zip",temp)
con <- unz(temp, "US.txt")
US <- read.delim(con, header=FALSE)
unlink(temp)
colnames(US)[c(3,5,6)] <- c("city","state","county")
CA<-filter(US, state== "CA")
US$city <- tolower(US$city)

County<-(US)[c(3,6)]


#join on city from charging station 

station <- read_csv("alt_fuel_stations.csv")
station$city <- tolower(station$city)
data<-left_join(station, County, by = "city")



```




```{r}

data$Open_Date <-mdy(data$Open_Date)

#https://blogs.oracle.com/datascience/introduction-to-forecasting-with-arima-in-r
summary(data)
class(data$Open_Date)
data$Year <- year(data$Open_Date)

```



```{r}


data%>%
ggplot(aes(x=Open_Date, y=data$`EV Level2 EVSE Num`))+
  geom_line() + scale_x_date('month')+ 
    ylab("Count of Charging Stations Opened in Year X") +
    xlab("Date")


```


##creating counts for level 2 and DC by county by open data, cummulativly add prior years stations 

```{r}
data<-as.data.frame(data)

stationCounty <- data%>%
  group_by(county)%>%
  aggregate(data["Year"], by= list(year = Year), FUN= sum)



```








