---
title: "final_forecast_Var"
author: "Arun Sharma"
date: "5/8/2021"
output: html_document
---


```{r}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(reshape2)

rm(list = ls())
```

# Load datasets

## population
```{r}
#Population
pop <- read.csv("population.csv")

#select only relevant rows
pop <- pop[1:59,1:27]

#remove county from names
pop$Region <- gsub(" County", "", pop$Region)

#remove x from cols
names(pop) <- gsub("X","", names(pop))

long_pop <- melt(pop, id.vars = c("Region"))

names(long_pop)[2] <- "year"
names(long_pop)[3] <- "population"
names(long_pop)[1] <- "county"
long_pop$year <- as.numeric(as.character(long_pop$year))
long_pop$county <- tolower(long_pop$county)
long_pop$county <- gsub("[^a-zA-Z]", "", long_pop$county)
```

## Income
```{r}
#Income
income <- read.csv("forecastedIncome.csv")
income <- income[,c(2:length(names(income)))]
county_names <- names(income)
county_names <-county_names[-length(county_names)]
county_names <- tolower(county_names)
county_names <- gsub("[^a-zA-Z]", "", county_names)
```

## Charging Stations
```{r}
chargers1 <- read.csv("county_datapoints.csv")
chargers1$county <- tolower(chargers1$county)
chargers1$county <- gsub("[^a-zA-Z]", "", chargers1$county)
# chargers1 %>% 
#   group_by(year) %>% 
#   summarise(total =sum(csum))

#chargers forecast
char_for <- read.csv("charger_forecast.csv")
charger_X <-  char_for[char_for$year_list>2020,]
names(charger_X)[2] <- "forecast_charger"
charger_X$county <- tolower(charger_X$county)
charger_X$county <- gsub("[^a-zA-Z]", "", charger_X$county)

```


## Fuel price -Gas
```{r}
#Fuel Price
fuel_price <- read.csv("CA_GasPreds_1995_2035.csv")
names(fuel_price) <- c("Date", "GasPrice_gal")
fuel_price$Date <- as.Date(fuel_price$Date, format = "%m/%d/%Y")
fuel_price$year <- year(fuel_price$Date)
f <- fuel_price %>% 
  group_by(year) %>% 
  summarise(avg_price = mean(GasPrice_gal))

gas_price <- f[f$year>2010,]
names(gas_price)[2] <- "gas_price"
```


## Vehicle price
```{r}
#Vehicle price
vehicle_price <- read.csv("cec_price_range.csv")
names(vehicle_price)[1] <- "year"
```

## Miles per KWH

```{r}
#Miles per kwh
mpk <- read.csv("forecastedMPKwh.csv")
mpk <- mpk[,c(2:length(names(mpk)))]
names(mpk)[1] <- "year"
```
## Y- Number of vehicles sold

```{r}
Y <- read.csv("numEV_CountyandYear.csv")
Y <- dplyr::select(Y, -X)
Y$county <- tolower(Y$county)
Y$county <- gsub("[^a-zA-Z]", "", Y$county)
yearly_sales <- Y %>% 
  group_by(year) %>% 
  summarise(total_sales = sum(num_ev, na.rm = TRUE))
```

```{r}
final <- merge(Y, gas_price, by = "year")
final <- merge(final, vehicle_price, by = "year")
final <- merge(final, mpk, by = "year")

final <- merge(final, long_pop, by = c("county", "year")) 

#lose rows over here
final <- merge(final, chargers1[,c("county","year","csum")], by = c("county", "year"))
final2 <- final

counties_10_values <- final2 %>% 
  group_by(county) %>% 
  mutate(total = n()) %>% 
  filter(total == 10)

predict_county <- final[final$county %in% counties_10_values$county,]
```

```{r}
library(urca)
library(vars)
library(mFilter)
library(tseries)
library(forecast)
income <- read.csv("forecastedIncome.csv")
cal_mean_income <- apply(income,1,mean)
income$california <- cal_mean_income
cal_income <- income[,c("california", "year")]
income_x <- cal_income[cal_income$year>2010 & cal_income$year <=2020,]
var_data <- final2 %>% 
  group_by(year) %>% 
  summarise(num_ev = sum(num_ev), gas_price = mean(gas_price), low = mean(low),
            medium = mean(medium), high = mean(high), m_p_k = mean(m_p_k), 
            population = sum(population), csum =sum(csum))
var_data$avg_price <- (var_data$low +var_data$medium +var_data$high)/3

chargers_ts <- ts(var_data$csum, start = 2011, frequency = 1)
vehicle_ts <- ts(var_data$num_ev, start = 2011, frequency = 1)
gas_ts <- ts(var_data$gas_price, start =2011, frequency =1)
pop_ts <- ts(var_data$population, start =2011, frequency =1)
mpk_ts <- ts(var_data$m_p_k, start =2011, frequency =1)
avg_price_ts <- ts(var_data$avg_price, start =2011, frequency =1)
cal_income_ts <- ts(income_x$california, start =2011, frequency =1)


autoplot(cbind(chargers_ts, vehicle_ts, gas_ts))
acf(chargers_ts)
pacf(chargers_ts)
```

#county wise var
## not much useful- getting unreasonable results
```{r}
counties_unique <- unique(predict_county$county)
for (i in 1:15){
  print(counties_unique[i])
  var_data <- final2[final2$county == counties_unique[i],] %>% 
  group_by(year) %>% 
  summarise(num_ev = sum(num_ev), gas_price = mean(gas_price), low = mean(low),
            medium = mean(medium), high = mean(high), m_p_k = mean(m_p_k), 
            population = sum(population), csum =sum(csum))
var_data$avg_price <- (var_data$low +var_data$medium +var_data$high)/3

chargers_ts <- ts(var_data$csum, start = 2011, frequency = 1)
vehicle_ts <- ts(var_data$num_ev, start = 2011, frequency = 1)
gas_ts <- ts(var_data$gas_price, start =2011, frequency =1)
pop_ts <- ts(var_data$population, start =2011, frequency =1)
mpk_ts <- ts(var_data$m_p_k, start =2011, frequency =1)
avg_price_ts <- ts(var_data$avg_price, start =2011, frequency =1)
cal_income_ts <- ts(income_x$california, start =2011, frequency =1)

bind_data <- cbind(chargers_ts,vehicle_ts)
colnames(bind_data) <- cbind("Chargers", "Vehicles")

lagSelect <- VARselect(bind_data, lag.max = 8, type = "trend")
lagSelect$selection

model1 <- VAR(bind_data, p =1, type="trend", season = NULL, exogen = NULL)
# summary(model1)
forecast <- predict(model1, n.ahead =15, ci=0.95)
fanchart(forecast, names = "Vehicles")
final <- data.frame(forecast$fcst)
forecast_num <- final[,c(5:8)]

var_data[,c(1,2)]
forecast_num$year <- 0
j =1
for (i in 2021:2035){
  
  forecast_num[j,"year"] <- i
  print
  j = j+1
}
f1 <- forecast_num[,c("Vehicles.fcst", "year")]
names(f1) <- c("num_ev","year")
data_forecasted <- rbind(var_data[,c(1,2)], f1)

}
```

#model- has all the variables
```{r}
#finding optimal lags
bind_data <- cbind(chargers_ts,vehicle_ts, gas_ts, pop_ts, mpk_ts, avg_price_ts)
colnames(bind_data) <- cbind("Chargers", "Vehicles", "GasPrices", "Population", "MPK", "AvgPrice")

lagSelect <- VARselect(bind_data, lag.max = 8, type = "trend")
lagSelect$selection

model1 <- VAR(bind_data, p =1, type="trend", season = NULL, exogen = NULL)
# summary(model1)




#forecasting

forecast <- predict(model1, n.ahead =15, ci=0.95)
fanchart(forecast, names = "Vehicles")

#var restrictions
amat <- diag(2)

final <- data.frame(forecast$fcst)
forecast_num <- final[,c(5:8)]

var_data[,c(1,2)]
forecast_num$year <- 0
j =1
for (i in 2021:2035){
  
  forecast_num[j,"year"] <- i
  print
  j = j+1
}
f1 <- forecast_num[,c("Vehicles.fcst", "year")]
names(f1) <- c("num_ev","year")
data_forecasted_all <- rbind(var_data[,c(1,2)], f1)
# write.csv(data_forecasted, "VAR predictions.csv")

ggplot(data = data_forecasted_all, aes(x = year, y = num_ev))+
  geom_line(color = "green", size =1.2)+
  theme_bw()+
 labs(y = "Electric Vehicles Sold", x = "Year")+
  ggtitle("Forecasted number of New Vehicles in California", subtitle= "VAR model forecast with all the considered varibles")

```

## model has selected variables
```{r}
#finding optimal lags
bind_data <- cbind(chargers_ts,vehicle_ts,cal_income_ts)
colnames(bind_data) <- cbind("Chargers", "Vehicles","Income")

lagSelect <- VARselect(bind_data, lag.max = 8, type = "trend")
lagSelect$selection

model1 <- VAR(bind_data, p =1, type="trend", season = NULL, exogen = NULL)
# summary(model1)




#forecasting

forecast <- predict(model1, n.ahead =15, ci=0.95)
fanchart(forecast, names = "Vehicles")

#var restrictions
amat <- diag(2)

final <- data.frame(forecast$fcst)
forecast_num <- final[,c(5:8)]

var_data[,c(1,2)]
forecast_num$year <- 0
j =1
for (i in 2021:2035){
  
  forecast_num[j,"year"] <- i
  print
  j = j+1
}
f1 <- forecast_num[,c("Vehicles.fcst", "year")]
names(f1) <- c("num_ev","year")
data_forecasted <- rbind(var_data[,c(1,2)], f1)
write.csv(data_forecasted, "VAR predictions.csv")
data_forecasted$num_ev2 <- data_forecasted_all$num_ev
ggplot(data = data_forecasted, aes(x = year, y = num_ev))+
  geom_line(color = "green", size =1.2)+
  geom_line(aes( y=num_ev2), color = "orange")+
  theme_bw()+
 labs(y = "Electric Vehicles Sold", x = "Year")+
  ggtitle("Forecasted number of New Vehicles in California", subtitle= "VAR model forecast with different variables")+
  annotate("text", x = 2032, y = 200000, label = "All Variables included", color = "orange")+
  annotate("text", x = 2027, y = 1250000, label = "Only Chargers and Median Income", color = "green")
  

```

```{r}

```

