---
title: "Policy_Scen_EV"
author: "ClareCallahan"
date: "4/26/2021"
output: html_document
---

Background: 
Tesla reached the milestone in July 2018 and General Motors reached it in December 2018. No other automaker is likely to reach the 200,000 unit sales threshold until at least 2022-2023.

2022-2030


https://evadoption.com/ev-sales/federal-ev-tax-credit-phase-out-tracker-by-automaker/#:~:text=Updated%20through%20June%202020&text=Tesla%20reached%20the%20milestone%20in,until%20at%20least%202022%2D2023.

```{r setup, include=FALSE}
#install.packages('did')
#install.packages('Hmisc')

library(did)

library(tidyverse)

#library(Hmisc)
```

```{r}
dmv <-read.csv("dmv_data.csv", header = TRUE)

dmv$Data.Year<- as.numeric(dmv$Data.Year)
 #dmv<- subset(dmv, Fuel.Type =="Electric"| Fuel.Type=="PHEV") 
 
 dmv<- subset(dmv, Data.Year>=2015)
 head(dmv)

```
Comparision selection
```{r}



drops <- c("TESLA", "CHEVROLET") 

other2 <- subset(dmv, !(MAKE %in% drops))

ggplot(dmv, aes(x=Data.Year,y=Number.of.Vehicles, fill=MAKE))+
  stat_summary(fun.data = mean_cl_normal)+
  geom_smooth(method='lm', formula=y~x)

lm_dmv<-lm(Number.of.Vehicles ~ Data.Year + MAKE, dmv)
summary(lm_dmv)



ggplot(subset(dmv, MAKE=="BMW"), aes(x=Data.Year,y=Number.of.Vehicles, fill=MAKE))+
  stat_summary(fun.data = mean_cl_normal)+
  geom_smooth(method='lm', formula=y~x)

ggplot(subset(dmv, MAKE=="Audi"), aes(x=Data.Year,y=Number.of.Vehicles, fill=MAKE))+
  stat_summary(fun.data = mean_cl_normal)+
  geom_smooth(method='lm', formula=y~x)


ggplot(subset(dmv, MAKE=="CHEVROLET"), aes(x=Data.Year,y=Number.of.Vehicles, fill=MAKE))+
  stat_summary(fun.data = mean_cl_normal)+
  geom_smooth(method='lm', formula=y~x)+
  geom_point()




```

## trial- Arun
```{r}
vehicle <- dmv %>% 
  group_by(Data.Year,MAKE) %>% summarise(total_veh = sum(Number.of.Vehicles))

#have both chev and tesla
vehicle1 <- vehicle
vehicle1$is.tesl_or_chev <- "Others"
vehicle1[vehicle1$MAKE %in% c("TESLA", "CHEVROLET"),]$is.tesl_or_chev <- "Tesla Or Chev"
# ggplot(data = vehicle, aes(x = Data.Year, y = total_veh))+
#   geom_line()+
#   facet_wrap(.~MAKE)
vehicle2 <- vehicle1 %>% 
  group_by(Data.Year, is.tesl_or_chev) %>% 
  summarise(total_veh = sum(total_veh))
ggplot(data = vehicle2, aes(x = Data.Year, y = total_veh, color = is.tesl_or_chev ))+
  geom_line() + ggtitle("Trends for both categories of vehicles", subtitle = "Both chev and tesla included")

#remove tesla
vehicle1 <- vehicle
vehicle1 <- vehicle1[!(vehicle1$MAKE %in% "TESLA"),]
vehicle1$is.chev <- "Others"
vehicle1[vehicle1$MAKE %in% c("CHEVROLET"),]$is.chev <- "Chev"

vehicle2 <- vehicle1 %>% 
  group_by(Data.Year, is.chev) %>% 
  summarise(total_veh = sum(total_veh))
ggplot(data = vehicle2, aes(x = Data.Year, y = total_veh, color = is.chev ))+
  geom_line() + ggtitle("Trends for both categories of vehicles", subtitle = "Only Chevrolet")

#assign post treatment world
vehicle2$after.treat <- 0
vehicle2[vehicle2$Data.Year > 2018,]$after.treat <- 1

vehicle2$is.treat <- 0
vehicle2[vehicle2$is.chev == "Chev",]$is.treat = 1

lm1 <- lm(total_veh~is.treat*after.treat, data = vehicle2)
summary(lm1)

```

```{r}

per<- cbind(tesla$Total, gm$Total, other$Total, tesla$Data.Year)


( sum(tesla$Total)+sum(gm$Total))/(sum(other$Total)+ sum(tesla$Total)+sum(gm$Total))



tesla <- subset(dmv, MAKE =="TESLA")

gm<- subset(dmv, MAKE=="CHEVROLET")

nissan_control <-subset(dmv, MAKE=="NISSAN")
toyota_control <-subset(dmv, MAKE=="Toyota")
                        
                        
                        #MAKE=="NISSAN"|MAKE=="FORD" | MAKE=="Hyundia"| MAKE=="Honda"| MAKE=="Kia"| MAKE=="NISSAN"| MAKE=="Volkswagen" )

drops <- c("TESLA", "CHEVROLET") 

other <- subset(dmv, !(MAKE %in% drops))

test <- dmv%>%
  group_by(Data.Year, MAKE)%>%
  summarise(Total = sum(Number.of.Vehicles, na.rm = TRUE),
            )

toyota_control <- toyota_control%>%
  group_by(Data.Year)%>%
  summarise(Total = sum(Number.of.Vehicles, na.rm = TRUE),
            )

nissan_control <- nissan_control%>%
  group_by(Data.Year)%>%
  summarise(Total = sum(Number.of.Vehicles, na.rm = TRUE),
            )

other <- other%>%
  group_by(Data.Year)%>%
  summarise(Avg = mean(Number.of.Vehicles, na.rm = TRUE), 
            Total = sum(Number.of.Vehicles)
            )


## need to use sum for treatment and avg for control
gm <- gm%>%
  group_by(Data.Year)%>%
  summarise(Total = sum(Number.of.Vehicles))


tesla <- tesla%>%
  group_by(Data.Year)%>%
  summarise(Total = sum(Number.of.Vehicles))

```
##Paralel trends 

conditional_did_pretest
Pre-Test of Conditional Parallel Trends Assumption

```{r}


ggplot(subset(dmv, MAKE== 'Audi'), aes(x=Data.Year,y=Number.of.Vehicles, fill=MAKE))+
  stat_summary(fun.data = mean_cl_normal)+
  geom_smooth(method='lm', formula=y~x)

ggplot(other2, aes(x=Data.Year,y=Number.of.Vehicles ))+
  stat_summary(fun.data = mean_cl_normal)+
  geom_smooth(method='lm', formula=y~x)+
  geom_point()

ggplot(other, aes(x=Data.Year,y=Avg ))+
  stat_summary(fun.data = mean_cl_normal)+
  geom_smooth(method='lm', formula=y~x)+
  geom_point()


ggplot(other, aes(x=Data.Year,y=Total ))+
  stat_summary(fun.data = mean_cl_normal)+
  geom_smooth(method='lm', formula=y~x)+
  geom_point()
```

```{r}

ggplot(gm, aes(x=Data.Year,y=Total))+
  stat_summary(fun.data = mean_cl_normal)+
  geom_smooth(method='lm', formula=y~x)+
  geom_point()

ggplot(tesla, aes(x=Data.Year,y=Total ))+
  stat_summary(fun.data = mean_cl_normal)+
  geom_smooth(method='lm', formula=y~x)+
  geom_point()



#ggplot(nissan_control, aes(x=Data.Year,y=Total ))+
 # stat_summary(fun.data = mean_cl_normal)+
  #geom_smooth(method='lm', formula=y~x)+
  #geom_point()


ggplot(toyota_control, aes(x=Data.Year,y=Total ))+
  stat_summary(fun.data = mean_cl_normal)+
  geom_smooth(method='lm', formula=y~x)+
  geom_point()

```


##Using Other Total

```{r}


other2= other[,-2]

other2<-subset(other2, Data.Year>= 2010)

other2$id <- "other"
gm$id <- "gm"
other2<-other2%>% rename(y = Total)
gm2<-gm%>% rename(y = Total)
df2 <- rbind(other2, gm2)


df2$time <- ifelse(df2$Data.Year >=2019, 1,0)
df2$treated <- ifelse(df2$id =="gm", 1,0)
df2$did= df2$time* df2$treated



didreg =lm(y~ treated +time+did, data=df2)

summary(didreg)

```

```{r}

other3= other[,-3]

other3<-subset(other3, Data.Year>= 2010)

other3$id <- "other"

other3<-other3%>% rename(y = Avg)

df2 <- rbind(other3, gm2)


df2$time <- ifelse(df2$Data.Year >=2019, 1,0)
df2$treated <- ifelse(df2$id =="gm", 1,0)
df2$did= df2$time* df2$treated

head(df2)

didreg =lm(y~ treated +time+did, data=df2)

summary(didreg)



```


```{r}


toyota <-toyota_control
toyota$id <- "toyota"
gm$id <- "gm"
toyota<-toyota%>% rename(y = Total)
gm2<-gm%>% rename(y = Total)
df3 <- rbind(toyota, gm2)


df3$time <- ifelse(df3$Data.Year >=2019, 1,0)
df3$treated <- ifelse(df3$id =="gm", 1,0)
df3$did= df3$time* df3$treated



didreg3 =lm(y~ treated +time+did, data=df3)

summary(didreg3)

9089/15136


```


