---
title: "regression_forecast v1_1"
author: "Arun Sharma"
date: "4/24/2021"
output: html_document
---

> Load packages

```{r}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(reshape2)

rm(list = ls())
```

# Load datasets


## population
```{r}
#Population
pop <- read.csv("population.csv")

#select only relevant rows
pop <- pop[1:59,1:27]

#remove county from names
pop$Region <- gsub(" County", "", pop$Region)

#remove x from cols
names(pop) <- gsub("X","", names(pop))

long_pop <- melt(pop, id.vars = c("Region"))
names(long_pop)[2] <- "year"
names(long_pop)[3] <- "population"
names(long_pop)[1] <- "county"
long_pop$year <- as.numeric(as.character(long_pop$year))
long_pop$county <- tolower(long_pop$county)
long_pop$county <- gsub("[^a-zA-Z]", "", long_pop$county)
```

## Income
```{r}
#Income
income <- read.csv("forecastedIncome.csv")
income <- select(income, -X)

county_names<- names(income)
income$year<- 2000:2035
income <-subset(income, year >=2010)
col_idx <- grep("^year$", names(income))
income <- income[, c(col_idx, (1:ncol(income))[-col_idx])]
income.long <- pivot_longer(income, cols = 2:59, names_to = "county" , values_to= "avg_income")
income.long$county <- tolower(income.long$county)
income.long$county <- gsub("[^a-zA-Z]", "", income.long$county)

```

## Charging Stations

```{r}
#Charging Station
chargers <- read.csv("county_chargers.csv")

#charging
chargers1 <- read.csv("county_datapoints.csv")
chargers1$county <- tolower(chargers1$county)
chargers1$county <- gsub("[^a-zA-Z]", "", chargers1$county)

#charger_forecast
charger_forecast <- read.csv("charger_forecast.csv")
names(charger_forecast)[2] <- "chargers"

#chargers forecast
char_for <- read.csv("charger_forecast.csv")
charger_X <-  char_for[char_for$year_list>2020,]
names(charger_X)[2] <- "forecast_charger"
charger_X$county <- tolower(charger_X$county)
charger_X$county <- gsub("[^a-zA-Z]", "", charger_X$county)
charger_forecast<-rename(charger_forecast, c('year'= 'year_list'))
charger_forecast$county <- tolower(charger_forecast$county)
charger_forecast$county <- gsub("[^a-zA-Z]", "", charger_forecast$county)
```


## Fuel price-Gas
```{r}
#Fuel Price
fuel_price <- read.csv("CA_GasPreds_1995_2035.csv")
names(fuel_price) <- c("Date", "GasPrice_gal")
fuel_price$Date <- as.Date(fuel_price$Date, format = "%m/%d/%Y")
fuel_price$year <- year(fuel_price$Date)
f <- fuel_price %>% 
  group_by(year) %>% 
  summarise(avg_price = mean(GasPrice_gal))

gas_price <- f[f$year>2010,]
names(gas_price)[2] <- "gas_price"
```


## Vehicle price ##updated Vehicle price with new CSV
```{r}
#Vehicle price
vehicle_price <- read.csv("Vehicle_prices_final.csv")
names(vehicle_price)[1] <- "year"
```

## Miles per KWH

```{r}
#Miles per kwh
mpk <- read.csv("forecastedMPKwh.csv")
mpk <- select(mpk, -X)
names(mpk)[1] <- "year"
```

### Kw prices (All of CA)
```{r}
kw_prices<-read.csv("yearly_kwh_prices.csv")
kw_prices <-subset(kw_prices, year >=2010)
```

## Y- Number of vehicles sold

```{r}
Y <- read.csv("numEV_CountyandYear.csv")
Y <- dplyr::select(Y, -X)
Y$county <- tolower(Y$county)
Y$county <- gsub("[^a-zA-Z]", "", Y$county)
yearly_sales <- Y %>% 
  group_by(year) %>% 
  summarise(total_sales = sum(num_ev, na.rm = TRUE))
```

## Merging data for Xs and Y

```{r}
final <- merge(Y, gas_price, by = "year")
final <- merge(final, vehicle_price, by = "year")
final <- merge(final, mpk, by = "year")
final <-merge(final, kw_prices, by= "year")
final <- merge(final, long_pop, by = c("county", "year")) 
final<- right_join(final, income.long, by= c("county", "year"))

#lose rows over here
final <- merge(final, chargers1[,c("county","year","csum")], by = c("county", "year"))
final2 <- final

model_data <- select(final, -c("year", "county"))

#preping data for model

#scale
Xs <- names(model_data)[2:6]
for (i in Xs ){
  print(model_data[,i])
}

scaled_model_data <- model_data
scaled_model_data$gas_price <- c(scale(model_data$gas_price, center = TRUE, scale = TRUE))

scaled_model_data$m_p_k<- c(scale(model_data$m_p_k, center = TRUE, scale = TRUE))

scaled_model_data$population<- c(scale(model_data$population, center = TRUE, scale = TRUE))

scaled_model_data$csum <- c(scale(model_data$csum, center = TRUE, scale = TRUE))

scaled_model_data$avg_income <- c(scale(model_data$avg_income, center = TRUE, scale = TRUE))
```

## Linear model
```{r}

lm1 <- lm(num_ev~., data=model_data)
summary(lm1)

lm2 <- lm(num_ev~., data=scaled_model_data)
summary(lm2)

## predictions with model

### get the X's for future


#gas X
gas_price_X <- gas_price[gas_price$year>2020,]

#m_p_k X
mpk_X <- mpk[mpk$year > 2020,]

#vehicle_price X
vehicle_price_X <- vehicle_price[vehicle_price$year > 2020,]

#chargers
c_X <- charger_X %>% 
  group_by(year_list) %>%
  summarise(csum = sum(forecast_charger))
names(c_X)[1] <- "year"

#population
x_pop <- long_pop[long_pop$year>2020 & long_pop$county == "california",] 

#cbind Xs
X_pred <- cbind(gas_price_X[,c("gas_price")],
               m_p_k =mpk_X[,c("m_p_k")], vehicle_price_X[,c("low","medium", "high")],
                c_X[,c("csum")], population = x_pop[,c("population")])


X_pred$csum <- chargers_forecast$total_chargers
x_new_model <- X_pred

#combining prices for all category

X_pred$avg_income <- (X_pred$low + X_pred$medium + X_pred$high)/3

X_pred <- select(X_pred, -c( "low", "medium", "high"))


```
```{r}
#var_data <- final2 %>% 
#  group_by(year) %>% 
#  summarise(num_ev = sum(num_ev), gas_price = mean(gas_price), low_price = mean(low),
        #    medium = mean(medium), high = mean(high), m_p_k = mean(m_p_k), 
       #     population = sum(population), csum =sum(csum))

#lm_Cal <- lm(num_ev~., data= var_data[,c(2:9)])
#summary(lm_Cal)
#prediction <- predict(lm_Cal, x_new_model, se.fit = TRUE)

#preds <- as.data.frame(matrix(0,nrow=15, ncol =2))

#names(preds) <- c("year", "num_ev")

# preds[1,1]

#j=1
#for (i in 2021:2035){
#  preds[j,1] <- i
#  j=j+1
#}

#preds$`num_ev` <- prediction$fit
#f_cal <- var_data[,c("year", "num_ev")]

#lm_data <- rbind(f_cal, preds)

#ggplot(data = lm_data, aes(x=year, y =num_ev))+geom_line()
```

## VAR model
```{r}
library(urca)
library(vars)
library(mFilter)
library(tseries)
library(forecast)

var_data <- final2 %>% 
  group_by(year) %>% 
  summarise(num_ev = sum(num_ev), gas_price = mean(gas_price), low = mean(low),
            mid = mean(mid), high = mean(high), m_p_k = mean(m_p_k), 
            population = sum(population), csum =sum(csum), avg_income=mean(avg_income), dollar.per.kw= mean(dollar.per.kw))

chargers_ts <- ts(var_data$csum, start = 2011, frequency = 1)
vehicle_ts <- ts(var_data$num_ev, start = 2011, frequency = 1)
gas_ts<- ts(var_data$gas_price, start = 2011, frequency = 1)
low_v_ts<- ts(var_data$low, start = 2011, frequency = 1)
mid_v_ts<- ts(var_data$mid, start = 2011, frequency = 1)
high_v_ts<- ts(var_data$high, start = 2011, frequency = 1)
mpk_v_ts<- ts(var_data$m_p_k, start = 2011, frequency = 1)
pop_v_ts<- ts(var_data$population, start = 2011, frequency = 1)
income_v_ts<- ts(var_data$avg_income, start = 2011, frequency = 1)
price.per.kw_ts<- ts(var_data$dollar.per.kw, start = 2011, frequency = 1)


autoplot(cbind(chargers_ts, vehicle_ts, gas_ts, low_v_ts, mid_v_ts, high_v_ts, mpk_v_ts, pop_v_ts, income_v_ts, price.per.kw_ts))



acf(chargers_ts)
pacf(chargers_ts)

#finding optimal lags
bind_data <- cbind(chargers_ts, vehicle_ts, gas_ts, low_v_ts, mid_v_ts, high_v_ts, mpk_v_ts, pop_v_ts, income_v_ts, price.per.kw_ts)


colnames(bind_data) <- cbind("Chargers", "Vehicles", "Gas", "LowPrice", "MidPrice", "HighPrice", "Mile_Kw", "Population", "Avg_Income", "Price_Kw")

bind_data<-na.omit(bind_data)

lagSelect <- VARselect(bind_data, lag.max = 8, type = "trend")
lagSelect$selection

model1 <- VAR(bind_data, p =1, type="trend", season = NULL, exogen = NULL)
summary(model1)

#diaganose
#serial correaltion

#heteroskedasticity

#normal

# Stability


#granger causality

#grangercharger <- causality(model1, cause = "Chargers")
#grangercharger

#grangervehicle <- causality(model1, cause = "Vehicles")
#grangervehicle

#impulse response functions
#vehicleirf <- irf(model1, impulse = "Chargers", response = "Vehicles", n.ahead =15, boot= TRUE)

#plot(vehicleirf, ylab = "vehicles")

#variance decomposition

#vvd <- fevd(model1, n.ahead = 10)
#plot(vvd)

#forecasting

forecast <- predict(model1, n.ahead =15, ci=0.95)
#fanchart(forecast, names = "Vehicles")

#var restrictions
amat <- diag(2)

final <- data.frame(forecast$fcst)
forecast_num <- final[,c(5:8)]

var_data[,c(1,2)]
forecast_num$year <- 0


j =1
for (i in 2021:2035){
  
  forecast_num[j,"year"] <- i
  print
  j = j+1
}


f1 <- forecast_num[,c("Vehicles.fcst", "year")]
names(f1) <- c("num_ev","year")
data_forecasted <- rbind(var_data[,c(1,2)], f1)


write.csv(data_forecasted, "VAR predictions.csv")

ggplot(data = data_forecasted, aes(x = year, y = num_ev))+geom_line()

```


```{r}

var_data <- final2 %>% 
  group_by(year) %>% 
  summarise(num_ev = sum(num_ev), gas_price = mean(gas_price), low = mean(low),
            medium = mean(medium), high = mean(high), m_p_k = mean(m_p_k), 
            population = sum(population), csum =sum(csum))

chargers_ts <- ts(var_data$csum, start = 2011, frequency = 1)
vehicle_ts <- ts(var_data$num_ev, start = 2011, frequency = 1)



   # Bounds
    a <- 0
    b <- 2000000
    
    
    # Transform data
    vehicles_t <- log((vehicle_ts-a)/(b-vehicle_ts))
    # charg_t <-log((vehicle_ts-c)/(d-vehicle_ts))
    
    bind_data <- cbind(chargers_ts,vehicles_t)
    colnames(bind_data) <- cbind("Chargers", "Vehicles")

lagSelect <- VARselect(bind_data, lag.max = 8, type = "trend")
lagSelect$selection

model1 <- VAR(bind_data, p =1, type="trend", season = NULL, exogen = NULL)
summary(model1)

    # fit <- ets(y)
    fc <- predict(model1, n.ahead =15, ci=0.95)
    # Back-transform forecasts
    fc$fcst$Vehicles[,1] <- (b-a)*exp(fc$fcst$Vehicles[,1])/(1+exp(fc$fcst$Vehicles[,1])) + a
    # fc$lower <- (b-a)*exp(fc$lower)/(1+exp(fc$lower)) + a
    # fc$upper <- (b-a)*exp(fc$upper)/(1+exp(fc$upper)) + a
    # fc$x <- eggs
    # Plot result on original scale
    plot(fc)
    
    fc$fcst$Vehicles[,1]
```


## predict for future

```{r}

prediction <- predict(lm1, X_pred, se.fit = TRUE)

pred.w.plim <- predict(lm1, X_pred, interval = "prediction")

pred.w.clim <- predict(lm1, X_pred, interval = "confidence")

matplot(X_pred$m_p_k, cbind(pred.w.clim, pred.w.plim[,-1]),
        lty = c(1,2,2,3,3), type = "l", ylab = "predicted y")

# length(prediction$fit)

preds <- as.data.frame(matrix(0,nrow=15, ncol =2))

names(preds) <- c("Year", "alameda_projections")

# preds[1,1]

j=1
for (i in 2021:2035){
  preds[j,1] <- i
  j=j+1
}

preds$`alameda_projections` <- prediction$fit
```

# use caret
```{r}
library(caret)
preproc <- preProcess(model_data[,c(2:6)], method = c("center", "scale"))
scaled.new <- predict(preproc, newdata = X_pred)

model <- train(num_ev ~ .,
               data = model_data,
               method = "lm",
               preProcess = c('scale', 'center'))
model$modelInfo
predictions <- predict(model, X_pred)
```

```{r}
prediction <- predict(lm2, scaled.new)
```

```{r}

write.csv(preds, "Prediction_california.csv")
```